### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by patrick-mcdougle** [jdiscar/vose-alias-method.js#1]
Thanks for writing and open sourcing this 😄  I notice that this repo has a package.json file, but I can't find it on NPM. Could you possibly publish it there? I would rather mark it as a dependency than copy it into my library.

**Comment by jdiscar** [comment]
Thanks for the suggestion! I added vose-alias-method to npm: https://www.npmjs.com/package/vose-alias-method

**Comment by patrick-mcdougle** [comment]
Appreciate it!
